# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    #branches:
    #  - master
    tags:
      - v.*
    
  #pull_request:
  #  branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.DOCKER_HUB_LOGIN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        echo $RELEASE_VERSION
        echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Build
      run: docker build -t $LOGIN/avl:latest -f alerter .
    - name: Build
      run: docker build -t $LOGIN/avl:$RELEASE_VERSION -f alerter .
      
    - name: Login to docker.io
      run:  echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} --password-stdin
      
    - name: Push image to docker.io
      run: docker push $LOGIN/avl:latest
    - name: Push image to docker.io
      run: docker push $LOGIN/avl:$RELEASE_VERSION


